services:
    ger.searchts.listener:
        class: ger\searchts\event\main_listener
        arguments:
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@template'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
